<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Akka.Serialization.MessagePack</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Akka.Serialization.V2\Akka.Serialization.V2.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MessagePack" />
  </ItemGroup>

</Project>
