<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Akka.Serialization.V2\Akka.Serialization.V2.csproj" />
    <ProjectReference Include="..\..\src\Akka.Serialization.Codec.MessagePack\Akka.Serialization.Codec.MessagePack.csproj" />
    <ProjectReference Include="..\..\src\Akka.Serialization.Generators\Akka.Serialization.Generators.csproj"
                      OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    <ProjectReference Include="..\..\tests\Akka.Serialization.V2.Tests\Akka.Serialization.V2.Tests.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" />
  </ItemGroup>

</Project>
